import Head from 'next/head'
import style from '../styles/Home.module.css'
import { ChangeEvent, FormEvent, useState } from 'react'
import Link from 'next/link'
import { obtener } from '../interfaces/persistenciaI'
import { AxiosError } from 'axios'
import { ObtenerClient } from '../services/servicesRES'

export default function comprobar() {
    const [persistencia, setpersistencia] = useState<obtener>({
        ci: ''
    });
    const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
        setpersistencia({
            ...persistencia,
            [e.target.name]: e.target.value,
        });
    };
    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        const {ci} = persistencia
        console.log( ci );
         ObtenerClient( ci )
              .then( ( res ) => {
                  console.log( res )
                    return (
                            <div>
                                    <div className="container">
                                    <div className="row">
                                        <br/>
                                        
                                            <table className="table table-striped">
                                                <thead>
                                                    <th>Numero de Prestamo</th>
                                                    <th>Fecha y Hora</th>
                                                    <th>Ci Estudiante</th>
                                                    <th>Tipo Cancha</th>
                                                    <th colSpan={2} >Opciones</th>
                                                </thead>
                                                {res.datos.length===0?(
                                                    <div >Cargando...</div>
                                                ):(
                                                    res.datos?.map((prestamo:any) => {
                                                        return (
                                                            <tr key={prestamo._id}>
                                                                <td>{prestamo.numerosprestamos}</td>
                                                                <td>{prestamo.fechayhora}</td>
                                                                <td>{prestamo.ciestudiante}</td>
                                                                <td>{prestamo.tipocancha}</td>
                                                                <td><Link className='btn btn-primary' href={`http://localhost:4500/nombreentidad/actualizar/${prestamo._id}}`}></Link></td>
                                                            </tr>
                                                            )
                                                    })
                                                )}
                                                
                                            </table>
                                    </div>
                            </div>
                            </div>
                    )
                } )
              .catch( ( error: AxiosError) => {
                  console.log( error)
              } )
    }

    return (
        <div>
            <Head>
                <title>Identificación</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"></link>
            </Head>
            <main className={style.main}>
                <h1 className="text-center">
                    Ingrese su cédula
                </h1>
                <div className="container">
                    <form onSubmit={handleSubmit} method="post">

                        <div className="form-group">
                            <label htmlFor="nombre">Cedúla</label>
                            <input onChange={handleChange} className="form-control" type="text" id="ci" name="ci" />
                        </div>

                        <button type="submit" className="btn btn-primary">Consultar</button>

                    </form>
                </div>
                <Link href='/' >
                    <a className="btn btn-primary">Atrás</a>
                </Link>
            </main>
        </div>
    )
}