import Head from 'next/head'
import style from '../styles/Home.module.css'
import {ChangeEvent, FormEvent, useState} from 'react'
import Link from 'next/link'
import { PersistenciaI } from '../interfaces/persistenciaI'
import { AxiosError } from 'axios'
//import { useRouter } from 'next/router'
import { crear } from '../services/servicesRES'

export default function Registro (){
    //const router = useRouter();
    
    const [persistencia, setpersistencia]= useState<PersistenciaI>({
        numerosprestamos: 0,
        fechayhora:'',
        ciestudiante:'',
        numerohoras:0,
        jugadoresparticipantes:'',
        tipocancha:'',
      });
    const handleChange = ( e: ChangeEvent<HTMLInputElement> ) => {
        setpersistencia( {
            ...persistencia,
            [e.target.name]: e.target.value,
        } );
    };
    const handleSubmit = ( e: FormEvent<HTMLFormElement> ) => {
        e.preventDefault()
        const dato = persistencia
        console.log( dato );
         crear( dato )
              .then( ( res ) => {
                  console.log( res )
                
              } )
              .catch( ( error: AxiosError) => {
                  console.log( error)
              } )
    }
    return (
        <div>
            <Head>
                <title>Identificación</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"></link>
            </Head>
            <main className={style.main}>
                <div className="container">
                    <form onSubmit={handleSubmit} method="post">
                    
                        <div className="form-group">
                            <label htmlFor="nombre">Numero de Prestamo</label>
                            <input  onChange={handleChange} className="form-control" type="number"  id="numerosprestamos" name="numerosprestamos"  />
                        </div>
                        <div className="form-group">
                            <label htmlFor="nombre">Fecha y Hora</label>
                            <input onChange={handleChange} className="form-control" type="datetime"  id="fechayhora" name="fechayhora"  />
                        </div>
                        <div className="form-group">
                            <label htmlFor="nombre">Identificación</label>
                            <input onChange={handleChange} className="form-control" type="text"  id="ciestudiante" name="ciestudiante"  />
                        </div>
                        <div className="form-group">
                            <label htmlFor="nombre">Numero de Horas</label>
                            <input onChange={handleChange} className="form-control" type="number"  id="numerohoras" name="numerohoras"  />
                        </div>
                        <div className="form-group">
                            <label htmlFor="nombre">Jugadores Que Participarán</label>
                            <input onChange={handleChange} className="form-control" type="textarea"  id="jugadoresparticipantes" name="jugadoresparticipantes"  />
                        </div>
                        <div className="form-group">
                            <label htmlFor="nombre">Tipo de Cancha</label>
                            <input onChange={handleChange} className="form-control" type="text"  id="tipocancha" name="tipocancha"  />
                        </div>
                    
                        <button type="submit" className="btn btn-primary">Enviar</button>
                
                    </form>
                </div>
                <Link href='/' >
                    <a   className="btn btn-primary">Atrás</a>
                 </Link> 
            </main>
        </div>
    )
}